// This file is auto-generated by scripts/build-automation-catalog.mjs.
// Do not edit it manually. To update it after changing automations/catalog/*/manifest.json,
// run: npm run build:automations

import entry0 from "./catalog/github-pr-reviewer/manifest.json" with { type: "json" };
import entry1 from "./catalog/github-repo-monitor/manifest.json" with { type: "json" };
import entry2 from "./catalog/slack-standup-digest/manifest.json" with { type: "json" };
import entry3 from "./catalog/slack-channel-monitor/manifest.json" with { type: "json" };
import entry4 from "./catalog/linear-triage-assistant/manifest.json" with { type: "json" };
import entry5 from "./catalog/jira-issue-to-pr/manifest.json" with { type: "json" };
import entry6 from "./catalog/research-brief-writer/manifest.json" with { type: "json" };
import entry7 from "./catalog/upstream-fork-sync/manifest.json" with { type: "json" };
import entry8 from "./catalog/incident-retrospective-drafter/manifest.json" with { type: "json" };

export const AUTOMATION_CATALOG_ENTRIES = [
  entry0,
  entry1,
  entry2,
  entry3,
  entry4,
  entry5,
  entry6,
  entry7,
  entry8,
];
